spring:
  data:
    mongodb:
      database: patient
      host: localhost
      port: 27017

  cloud:
    stream:
      bindings:
        input:
          destination: patient
          group: all.events
          binder: rabbit
        onPatientAddressAdded:
          destination: patient.address
          group: update.number.services
          binder: rabbit
        onServiceAdded:
          destination: service
          group: added
          binder: rabbit
        output:
          destination: patient
          binder: rabbit
      rabbit:
        bindings:
          onPatientAddressAdded:
            consumer:
              bindingRoutingKey: cinfantes.patient.1.event.patient.address.added
          onServiceAdded:
            consumer:
              bindingRoutingKey: cinfantes.service.1.event.service.added
          output:
            producer:
              routingKeyExpression: payload.type
      binders:
        rabbit:
          type: rabbit
