spring:
  data:
    mongodb:
      database: patient-address
      host: localhost
      port: 27017

  cloud:
    stream:
      bindings:
        output:
          destination: patient.address
          binder: rabbit
      rabbit:
        bindings:
          output:
            producer:
              routingKeyExpression: payload.type
      binders:
        rabbit:
          type: rabbit
